name       : quiterss
version    : 0.18.5
release    : 2
source     :
    - https://quiterss.org/files/0.18.5/QuiteRSS-0.18.5-src.tar.gz : af4aaffaebbcd9f10a210cd921085545f846716312aa85a7fe573d8c3a4549a7
license    : GPL-3.0
component  : network.util
summary    : QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader.
description: |
    QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader, fast and comfortable to use.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
build      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
install    : |
    %make_install
