name       : quiterss
version    : 0.18.8
release    : 4
source     :
    - https://quiterss.org/files/0.18.8/QuiteRSS-0.18.8-src.tar.gz : c83c6736b1331a6fd9b257fa91c282c504086704d0c69c483bb31c7c6759fe57
license    : GPL-3.0
component  : network.news
summary    : QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader.
description: |
    QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader, fast and comfortable to use.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
setup      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
