name       : quiterss
version    : 0.18.12
release    : 7
source     :
    - https://quiterss.org/files/0.18.12/QuiteRSS-0.18.12-src.tar.gz : 553461bcf266e62fc91aa93f7f6bde2176785dccf9311ded6c651ffe5d68fe6f
license    : GPL-3.0-or-later
component  : network.news
summary    : QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader.
description: |
    QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader, fast and comfortable to use.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(glu)
    - pkgconfig(sqlite3)
setup      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
