name       : quiterss
version    : 0.19.4
release    : 10
source     :
    - https://github.com/QuiteRSS/quiterss/archive/0.19.4.tar.gz : d9dffa205a8ec4e7bf00d87183fd94d4a12f045fae04a6efd41d6557827233bc
homepage   : https://quiterss.org
license    : GPL-3.0-or-later
component  : network.news
summary    : QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader.
description: |
    QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader, fast and comfortable to use.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(glu)
    - pkgconfig(sqlite3)
setup      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
