name       : quiterss
version    : 0.18.6
release    : 3
source     :
    - https://quiterss.org/files/0.18.6/QuiteRSS-0.18.6-src.tar.gz : 1162a7878110f8fab0257d31bcfd37ebcf9610ddefaf3f35cd4af8b606a1f066
license    : GPL-3.0
component  : network.util
summary    : QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader.
description: |
    QuiteRSS is a open-source cross-platform RSS/Atom news feeds reader, fast and comfortable to use.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
build      : |
    %qmake CONFIG+=release PREFIX=$installdir/usr
install    : |
    %make_install
